# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
- name: System.Debug
  value: true

jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    name: Default
  steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line script'

  - task: Application security testing@2024
    displayName: Application security testing
    inputs:
      projectName: 'RahulP-105'
      enableProxy: false
      enableSastScan: true
      CheckmarxService: 'SAST 67 server'
      enableSastBranching: false
      fullTeamName: 'CxServer'
      incScan: false
      generatePDFReport: true
      enableDependencyScan: false
  - task: CopyFiles@2
    inputs:
      SourceFolder: 'C:\agent\vsts-agent-win-x64-4.248.0\_work\4'
      Contents: 'cxReport_*.json'  # Supports wildcards but NOT regex
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
  
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'SecurityReports'
